[sel Main]
[s]Player Options[e]
[s]World Options[e]
[s]Check Phone[e]
[s]Misc[e]

[sel PLO]
[s]Model Size[e]
[s]Animation[e]

[sel WRO]
[s]Unused Maps[e]
[s]Cafe[e]

[sel MISC]
[s]FID Selector Test[e]
[s]About[e]

[msg MM [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 -1 0 0]Welcome to Kilos Menu! Made by [clr 9]Kilo[clr 0][n]
Thanks Shrinefox, TGE and Tekka. Press [clr 9]X[clr 0] to advance.[n][w][e]

[msg MMTEST [Test]]
[s][bup 0 3 0 0 0][f 4 10 -1 0 0]If you see this, your safe from the bugs for now.[n][w][e]